enabled: true

# HTTP代理地址
# 示例格式
# proxy:
#   http_proxy: http://127.0.0.1:1081
#   https_proxy: https://127.0.0.1:1081
proxy: {}

net:
  # SauceNAO 的API KEY, 支持多个以进行负载均衡, 每个KEY以换行分隔
  # api-key: |
  #   aaaaaaa
  #   bbbbbbb
  api-key: "149d6878c124d216c515327ab86230a1d7e83a51"

  keys: # SauceNAO 的API KEY, 支持多个以进行负载均衡
    - ""
  user-agent: &ua "Mozilla/5.0 (mixmoe@GitHub.com/HibiAPI) Chrome/114.514.1919810" # UA头, 一般没必要改

image:
  max-size: 4096 # 获取图片最大大小, 单位为 KBytes
  timeout: 6 # 获取图片超时时间, 单位为秒
  headers: { "user-agent": *ua } # 获取图片时携带的请求头
  allowed: # 获取图片的站点白名单, 可以阻止服务器ip泄漏, 支持通配符
    - localhost
    - i.loli.net
    - "*"
